---
version: '2.1'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:9200 || exit 1"]
      interval: 5s
      retries: 10

  kibana:
    image: rigon/kibana-dev:6.0.0
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    volumes:
      - ".:/kibana/plugins/kibana-own-home:rw"
      - "./kibana.yml:/kibana/config/kibana.yml:rw"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:5601 || exit 1"]
      interval: 5s
      retries: 10
